Feature ES modules
cine-estrenos/estrenos-api pull request #15
Opened 2019-07-04 19:57 UTC by lndgalante

This PR will:
- [x] Replace CommonJS with ES6 import/export
- [x] Rename variables to avoid repeated names
- [x] Add `.nvmrc` to be able to use `nvm use`
- [x] Adds babel-jest, @babel/core and @babel/preset-env to run Jest with ES Modules support
- [x] Add `fastify-cors` plugin
- [x] Bumps dependencies

2019-07-04 20:13 UTC, goncy requested changes
En general a mi no me molesta que los nombres sean los mismos, ya que agregarles `algoResolver` fuerza a una funcion a ser usada en un lugar en vez de la funcion declarar que es lo que hace, por ejemplo en este caso todo se llama `algoController` `algoResolver` pero no los selectors, por que quedaria feo llamarlos como `getMovieByIdSelector`, es mi punto de vista nomas, el resto genial, hay alguna ventaja nativa de usar modulos frente a commonjs como para que justifique agregar babel y eso?

2019-07-04 20:13 UTC, goncy commented on graphql/types/cinemas.js
> +import ApolloServerFastify from 'apollo-server-fastify';
no podemos hacer `import {gql} from 'apollo-server-fastify'`?

2019-07-04 20:13 UTC, goncy commented on graphql/types/index.js
> +
Mismo de arriba

2019-07-04 20:13 UTC, goncy commented on graphql/types/movies.js
> +const { gql } = ApolloServerFastify;
Mismo de arriba arriba

2019-07-04 20:13 UTC, goncy commented on graphql/types/shows.js
> +const { gql } = ApolloServerFastify;
Mismo de arriba arriba arriba

2019-07-04 20:13 UTC, goncy commented on plugins/apollo.js
> +const { ApolloServer } = ApolloServerFastify;
Mismo de arriba arriba arriba arriba

2019-07-04 20:13 UTC, goncy commented on resolvers/cinemas.js
> +const getCinemasResolver = async () => {
tambien podria ser `export default async function getCinemasResolver() {`

2019-07-04 20:44 UTC, lndgalante commented on graphql/types/cinemas.js
> +import ApolloServerFastify from 'apollo-server-fastify';
No, por como esta hecho el export, solo queda importar todo y después obtener `gql`.

2019-07-04 20:52 UTC, lndgalante commented on graphql/types/cinemas.js
> +import ApolloServerFastify from 'apollo-server-fastify';
No hay ninguna ventaja significativa de modulos frente a CommonJS, más que no hacer el context switch debido a que estamos acostumbrados a usar import como lo hacemos en el front, además que cuando ya esten incorporados en Node solamente tendríamos que remover los flags y las dependencias de babel que son necesarias para Jest. De igual manera seguimos corriendo el servidor sin necesidad de compilar.

2019-07-04 23:13 UTC, goncy commented on graphql/types/cinemas.js
> +import ApolloServerFastify from 'apollo-server-fastify';
Que soretes, que me exporten los no default tambien! genial entonces, padelante por mi

2019-07-04 23:59 UTC, lndgalante commented on resolvers/cinemas.js
> +const getCinemasResolver = async () => {
Cambiado!

2019-07-05 00:31 UTC, hdf1996 approved these changes

2019-07-05 00:36 UTC, merged